# Generated by Django 6.0.3 on 2026-04-04 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_order_product_orderitem_store_product_store_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
