# Generated by Django 6.0.3 on 2026-04-06 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_team_members_notice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('TL', 'Team Leader'), ('SR', 'Sales Representative')], default='SR', max_length=10),
        ),
    ]
